### ISSUE TITLE
Duplicate HUI results when itemset length >= 3

### ISSUE THREAD

**Issue by makhloufledmi** [ZaxR/itemset_mining#5]
I tried  to run the following example:
from itemset_mining.two_phase_huim import TwoPhase
from operator import attrgetter

transactions = [[("a", 6), ("b", 2.1), ("c", 1.5), ("d", 1.2)], [("e", 6), ("f", 2.1), ("g", 1.5),("h", 1.2)]]
external_utilities = {"a": 10, "b": 10, "c": 10, "d": 10, "e": 10, "f": 10, "g": 10, "h": 10}

minutil = 19

hui = TwoPhase(transactions, external_utilities, minutil)
result = hui.get_hui()
sorted(result, key=attrgetter('itemset_utility'), reverse=True)

I have got a wrong HUIs set.

I will be thankful for fixing this bug for me.

**Comment by ZaxR** [comment]
@Makh2018 - thanks for the report. Can you clarify your expected results? Running your code I see a lot of duplication, which I'll need to investigate, but are the results themselves as expected?

**Comment by makhloufledmi** [comment]
Thanks for the reply.
The results are not expected, but there is a lot of duplication when the size of itemset > 2:
HUIRecord(items=('a', 'b', 'c', 'd'), itemset_utility=108.0), ---------- 81
HUIRecord(items=('e', 'f', 'g', 'h'), itemset_utility=108.0), ---------- 81
HUIRecord(items=('a', 'b', 'c'), itemset_utility=96.0)        ---------- 27
HUIRecord(items=('e', 'f', 'g'), itemset_utility=96.0)        ---------- 27
HUIRecord(items=('a', 'b', 'd'), itemset_utility=93.0),       ---------- 27
HUIRecord(items=('e', 'f', 'h'), itemset_utility=93.0),       ---------- 27
HUIRecord(items=('a', 'c', 'd'), itemset_utility=87.0)        ---------- 27
HUIRecord(items=('e', 'g', 'h'), itemset_utility=87.0)        ---------- 27
HUIRecord(items=('a', 'b'), itemset_utility=81.0), 
HUIRecord(items=('e', 'f'), itemset_utility=81.0), 
HUIRecord(items=('a', 'c'), itemset_utility=75.0), 
HUIRecord(items=('e', 'g'), itemset_utility=75.0), 
HUIRecord(items=('a', 'd'), itemset_utility=72.0), 
HUIRecord(items=('e', 'h'), itemset_utility=72.0), 
HUIRecord(items=('a',), itemset_utility=60), 
HUIRecord(items=('e',), itemset_utility=60), 
HUIRecord(items=('b', 'c', 'd'), itemset_utility=48.0)        ---------- 27
HUIRecord(items=('f', 'g', 'h'), itemset_utility=48.0)        ---------- 27
HUIRecord(items=('b', 'c'), itemset_utility=36.0), 
HUIRecord(items=('f', 'g'), itemset_utility=36.0), 
HUIRecord(items=('b', 'd'), itemset_utility=33.0), 
HUIRecord(items=('f', 'h'), itemset_utility=33.0), 
HUIRecord(items=('c', 'd'), itemset_utility=27.0), 
HUIRecord(items=('g', 'h'), itemset_utility=27.0), 
HUIRecord(items=('b',), itemset_utility=21.0), 
HUIRecord(items=('f',), itemset_utility=21.0)]

**Comment by makhloufledmi** [comment]
I think that the bug is in the  _create_next_candidates  function
in this line: 
items = sorted(chain.from_iterable(prev_candidates))
that generates duplicate items.
Maybe this code fix the bug:
items = sorted(list(set(chain(*chain.from_iterable(prev_candidates)))))

**Comment by ZaxR** [comment]
Looks like that line is the issue, but the fix is even simpler - just need to add `set` to the mix:
```
items = sorted(set(chain.from_iterable(prev_candidates)))
```

Then the results look as expected to me:
```
[HUIRecord(items=('a', 'b', 'c', 'd'), itemset_utility=108.0),
 HUIRecord(items=('e', 'f', 'g', 'h'), itemset_utility=108.0),
 HUIRecord(items=('a', 'b', 'c'), itemset_utility=96.0),
 HUIRecord(items=('e', 'f', 'g'), itemset_utility=96.0),
 HUIRecord(items=('a', 'b', 'd'), itemset_utility=93.0),
 HUIRecord(items=('e', 'f', 'h'), itemset_utility=93.0),
 HUIRecord(items=('a', 'c', 'd'), itemset_utility=87.0),
 HUIRecord(items=('e', 'g', 'h'), itemset_utility=87.0),
 HUIRecord(items=('a', 'b'), itemset_utility=81.0),
 HUIRecord(items=('e', 'f'), itemset_utility=81.0),
 HUIRecord(items=('a', 'c'), itemset_utility=75.0),
 HUIRecord(items=('e', 'g'), itemset_utility=75.0),
 HUIRecord(items=('a', 'd'), itemset_utility=72.0),
 HUIRecord(items=('e', 'h'), itemset_utility=72.0),
 HUIRecord(items=('a',), itemset_utility=60),
 HUIRecord(items=('e',), itemset_utility=60),
 HUIRecord(items=('b', 'c', 'd'), itemset_utility=48.0),
 HUIRecord(items=('f', 'g', 'h'), itemset_utility=48.0),
 HUIRecord(items=('b', 'c'), itemset_utility=36.0),
 HUIRecord(items=('f', 'g'), itemset_utility=36.0),
 HUIRecord(items=('b', 'd'), itemset_utility=33.0),
 HUIRecord(items=('f', 'h'), itemset_utility=33.0),
 HUIRecord(items=('c', 'd'), itemset_utility=27.0),
 HUIRecord(items=('g', 'h'), itemset_utility=27.0),
 HUIRecord(items=('b',), itemset_utility=21.0),
 HUIRecord(items=('f',), itemset_utility=21.0)]
```

Re: the differing values in your comment above, how are you calculating those itemset utility values? For 
```HUIRecord(items=('a', 'b', 'c', 'd'), itemset_utility=108.0)```
that seems right to me based on the following calculation: 
6 * 10 (a) + 2.1 * 10 (b) + 1.5 * 10 (c) + 1.2 * 10 (d) = 108

**Comment by ZaxR** [comment]
Version `0.2.2` is now available via pypi with the duplication issue fixed.

**Comment by makhloufledmi** [comment]
Thank you very much.
